---
- name: Install docker
  apt:
    name: docker.io
    state: present

- name: Install modules docker
  pip:
    name: "{{ item }}"
  with_items:
    - docker

- name: Directory preparation
  file:
    path: /home/app
    state: directory
    mode: '0777'
  become: yes

- name: GET war file
  aws_s3:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: mybacket30.test4.com
    object: hello-1.0.war
    dest: /home/app/hello-1.0.war
    mode: get

- name: Create container
  docker_container:
    name: hello
    image: tomcat:alpine
    exposed_ports:
      - "8080:8080"
    volumes:
      - /home/app/:/usr/local/tomcat/webapps
    state: started
