---
- name: Update system
  apt: update_cache=yes

- name: Update and install system
  apt: name={{item}} state=present
  with_items:
    - default-jdk
    - python3
    - python3-pip

- name: Install modules boto3
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore