---
- name: Install default-jdk
  hosts: tag_group_build
  become: yes

  tasks:
    - name: Update system
      apt: update_cache=yes

    - name: Install jdk
      apt: name={{item}} state=present
        with_items:
          - default-jdk