---
- name: Application building
  hosts: tag_group_build
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - common
    - build

- name: Run application
  hosts: tag_group_run
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - common
    - run