---
- name: Install default-jdk
  hosts: tag_group_build
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt: name={{item}} state=present
        with_items:
          - default-jdk